### ISSUE TITLE
Upload values not displayed while test progress

### ISSUE THREAD

**Issue by iamredeye** [appscape/open-rmbt-ios#1]
Hi,

I would like first to thank you for the great job done on this project and I have learned a lot from the code written here.
But, I have noticed something strange, that the upload values are not displayed while le test progress in the "Upload" phase. This issue is only on iOS, in Android it is not the same thing.
Is it normal for the iOS version to act like this ? If not, how to fix that?

Thanks in advance

**Comment by esad** [comment]
This could happen if the upload speed is so low that not a single packet makes it through in the 7-8s timeframe (this duration is a parameter coming from the control server).

Are you having this issue in Simulator or on real device?

**Comment by iamredeye** [comment]
I'm having this issue on real device.
Here I have recorded a video of my iPhone 6 executing the test in RMBT-IOS.
https://www.dropbox.com/s/al2e7y2jj9qmd8h/IMG_0025.m4v?dl=0
Can I, by changing some parameters in control server, fix this issue ?
Thanks

**Comment by iamredeye** [comment]
Did you see my last comment ?

**Comment by esad** [comment]
This can only mean that for some reason the server's response to the first upload packet arrives couple of seconds later... Have you tried other speed tests on the same network and observed a similar result? What happens when you switch to 3g/4g?
