### ISSUE TITLE
What is the valid URL to be assigned to RMBT_CONTROL_SERVER_URL in RMBTConfig.h

### ISSUE THREAD

**Issue by epiphany27** [appscape/open-rmbt-ios#2]

**Comment by esad** [comment]
You will need to set-up your own server using https://github.com/alladin-IT/open-rmbt and then assign the URL in the config

**Comment by epiphany27** [comment]
Aah! I am an iOS guy. Zero knowledge about web-apps/server-side stuffs. Was wondering if there was a quick way to test the app with some default test URL. 
Thanks @esad .
