### ISSUE TITLE
Add support for 5G  / NR for 2020 iPhone Models

### ISSUE THREAD

**Issue by richietto** [appscape/open-rmbt-ios#4]
I believe RMBTConnectivity.m needs to be extended to detect 5G / NR properly on the 2020 iPhone models on iOS >= 14.1

new contants have been added on iOS docu

https://developer.apple.com/documentation/coretelephony/core_telephony_constants

let CTRadioAccessTechnologyNR: String
let CTRadioAccessTechnologyNRNSA: String

Can you pls add support for those new Radio technologies as well?

**Comment by esad** [comment]
The official repository has moved to https://github.com/rtr-nettest/open-rmbt-ios, please re-open this issue there
